// JW.UHF.Result
public enum Result {
  Antenna_Not_Configure = 19,
  Antenna_Not_Connected = 26,
  Antenna_Not_Exists = 14,
  Channel_Not_Supported = 20,
  Connect_Failure = 7,
  Device_Has_Disconnected = 28,
  Device_Is_Busy = 10,
  Disconnect_Failure = 8,
  Forward_Power_InSufficient = 27,
  Interface_Not_Avaliable = 18,
  Model_Not_Response = 4,
  Module_Is_Already_Opened = 3,
  Module_Is_Busy = 1,
  Module_Is_Closed = 2,
  Network_Exception = 22,
  OK = 0,
  Param_Error = 29,
  Parse_Packet_Data_Error = 24,
  Pwd_Is_Null = 12,
  Pwd_Length_Is_Error = 13,
  Read_Data_Is_Empty = 16,
  Receive_Buffer_OverFlow = 23,
  Response_TimeOut = 6,
  Reverse_Power_Too_Hign = 9,
  Sdk_Connect_TimeOut = 17,
  Send_Instruct_Failure = 5,
  Serial_Exception = 25,
  Unknown_Exception = 99,
  Wait_TimeOut = 15,
  Write_Data_Is_Null = 11,
  Write_Data_Too_Long = 21
}
